steps:
  - id: setup
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-e'
      - '-x'
      - '-c'
      - |
        # Your current directory is a workspace.
        gcloud auth list
        gsutil cp gs://dnastack-ci-content/bootstrap-workspace.tar.gz /tmp
        cd /tmp
        tar xzf bootstrap-workspace.tar.gz

        # Decrypt the .netrc (only required for compilation)
        gcloud kms decrypt --ciphertext-file=.netrc.enc --plaintext-file=.netrc --location=global --keyring=cloud-build-webhook --key=secret_key
        cp .netrc /root/
        rm .netrc
        chmod 600 /root/.netrc
    volumes:
      - name: 'homedir'
        path: /root

  - id: build_and_publish
    name: 'node:11'
    entrypoint: 'bash'
    args:
      - '-e'
      - '-x'
      - '-c'
      - |
        # Copy files to the home filder because the home folder is protected.
        cp -r /homedir_dotfiles/.??* /builder/home/

        npm login
        npm prepublish
        cd dist/ddap-common-lib
        npm version patch
        npm publish
    volumes:
      - name: 'homedir'
        path: /homedir_dotfiles

timeout: 3600s
logsBucket: dnastack-ci-logs
options:
  substitutionOption: ALLOW_LOOSE
  logStreamingOption: STREAM_ON
tags:  # NOTE: Run ID is set to "rogue" as a special ID for jobs not triggered by the webhook service.
  - "lib.ddap-libraries"
  - "pipeline"
  - "pipeline.run_id.rogue"
  - "pipeline.type.library-javascript"
  - "repo.ddap-libraries"
