steps:
  - id: setup
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-e'
      - '-x'
      - '-c'
      - |
        # Your current directory is a workspace.
        gcloud auth list
        gsutil cp gs://dnastack-ci-content/bootstrap-workspace.tar.gz /tmp
        cd /tmp
        tar xzf bootstrap-workspace.tar.gz

        # Decrypt the .netrc (only required for compilation)
        gcloud kms decrypt --ciphertext-file=.netrc.enc --plaintext-file=.netrc --location=global --keyring=cloud-build-webhook --key=secret_key
        cp .netrc /root/
        rm .netrc
        chmod 600 /root/.netrc

        # Decrypt the .netrc (only required for compilation)
        gcloud kms decrypt --ciphertext-file=.npmrc.enc --plaintext-file=.npmrc --location=global --keyring=cloud-build-webhook --key=secret_key
        cp .npmrc /root/
        rm .npmrc
        chmod 600 /root/.npmrc
    volumes:
      - name: 'homedir'
        path: /root

  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/DNAstack/ddap-libraries.git']

  - id: build_and_publish
    name: 'node:11'
    entrypoint: 'bash'
    args:
      - '-e'
      - '-x'
      - '-c'
      - |
        # Copy files to the home filder because the home folder is protected.
        cp -r /homedir_dotfiles/.??* /builder/home/

        # Verify node and npm version
        node -v
        npm -v

        npm install
        npm run prepublish
        cd dist/ddap-common-lib
        cp /builder/home/.npmrc .

        # With .npmrc in where "npm publish" running, "npm login" or "npm adduser" is not required.
        npm publish
    volumes:
      - name: 'homedir'
        path: /homedir_dotfiles

timeout: 3600s
options:
  substitutionOption: ALLOW_LOOSE
  logStreamingOption: STREAM_ON
tags:
  - "pipeline"
  - "pipeline.run_id.rogue"
  - "pipeline.type.library-javascript"
  - "repo.ddap-libraries"
